<?xml version="1.0" encoding="UTF-8"?>
<!--En un departamento se ha decidido la siguiente estructura para ficheros de 
datos que se tengan que mover de unos software a otros.
<!La raiz debe ser el elemento <listacompras>
<!Dentro de <listacompras> debe haber uno o mas elementos <venta>
Una venta puede llevar dentro uno de dos: <ventaacredito> o <ventainmediata>
Un elemento <ventaacredito> consta de : un elemento <fechafinpago> que es optativo y 
un elemento <cantidad> que es obligatorio.
Un elemento <ventainmediata> lleva dentro dos cosas: un elemento 
<cantidad> que es obligatorio y un elemento <divisa> que tambien es obligatorio -->
<!DOCTYPE listacompras [
    <!ELEMENT listacompras (venta+)>
    <!ELEMENT venta (ventaCredito | ventaInmediata)>
    <!ELEMENT ventaCredito (fechaFinPago?, cantidad)>
    <!ELEMENT fechaFinPago (#PCDATA)>
    <!ELEMENT cantidadCredito (#PCDATA)>
    <!ELEMENT ventaInmediata (cantidad, divisa)>
    <!ELEMENT cantidad (#PCDATA)>
    <!ELEMENT divisa (#PCDATA)>

]>
<listacompras>
    <venta>
        <ventaCredito>
            <fechaFinPago></fechaFinPago>
            <cantidad>88</cantidad>
        </ventaCredito>
    </venta>
</listacompras>
<!-- Ejercicio 4
Un mayorista de productos de libreria desea tener un formato de almacenamiento de datos para 
reflejar la informacion de su inventario.
El elemento raiz debe ser <inventario>
Dentro de inventario pueden ir elementos <lapiz>, <cuaderno> o <boligrafo> repetidos y 
en cualquier orden.
Todo <lapiz> puede tener un elemento <dureza>
Todo cuaderno debe llevar dos elementos: <numhojas> y <estilo>
Todo boligrafo lleva un <precio> y puede o no llevar un elemento <color -->
<!DOCTYPE 