=== OscarSTEM/LenguajeMarcas/Programadores.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">
  <xs:element name="listafacturas">
    <xs:complexType>
      <xs:sequence>
        <xs:element name="factura" maxOccurs="unbounded">
          <xs:complexType>
            <xs:attribute name="fecha" type="date"/>
            <xs:sequence>
                <xs:element name="emisor">
                    <xs.complexType>
                        <xs:element name="nombre" type="xs:string"/>
                        <xs:element name="descripcion" type="xs:string"/>
                    </xs:complextype>
                </xs.element>
                <xs:complexType>
                  <xs:sequence>
                    <xs:element name="dia" type="xs:integer" minOccurs="0"/>
                    <xs:element name="mes" type="xs:integer" minOccurs="0"/>
                    <xs:element name="anio" type="xs:integer" minOccurs="0"/>
                  </xs:sequence>
                </xs:complexType>
              </xs:element>
              <xs:element name="emisor">
                <xs:complexType>
                  <xs:sequence>
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="nombre" type="xs:string"/>
                            <xs:element name="volumenventas" type="xs:string" minOccurs="0"/>
                        </xs:sequence>
                        <xs:attribute name="cif" type="string" use="required"/>
                    </xs:complexType>
                  </xs:sequence>
                </xs:complexType>
              </xs:element>
              <xs:element>
            </xs:sequence>
          </xs:complexType>    
        </xs:element>
      </xs:sequence>
    </xs:complexType>
  </xs:element>
</xs:schema>

=== OscarSTEM/LenguajeMarcas/Programadores.xml
<?xml version="1.0" encoding="UTF-8"?>
<listafacturas xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
xsi:noNamespaceSchemaLocation="./Programadores.xsd">
   <factura fecha="12/08/1998">
      <nombre>Kingdom Hearts</nombre>
      <descripcion>Matar sincorazones</descripcion>
      <emisor>
        <emisor cif="5225">
        <nombre></nombre>
        <volumenventas></volumenventas>
        <importe></importe>

        </emisor>
    </factura>
</listafacturas>
